services:
  - type: web
    name: tooljet
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: TOOLJET_HOST
        value: "https://tooljet.onrender.com"
      - key: LOCKBOX_MASTER_KEY
        value: "your_lockbox_master_key"
      - key: DISABLE_TOOLJET_TELEMETRY
        value: "true"

databases:
  - name: tooljet-db
    plan: free
    region: oregon
