services:
  - type: web
    name: tooljet
    runtime: image            # ใช้ runtime: image ตามสเปค Render
    image: tooljet/tooljet-ce:latest
    plan: free                # ทดสอบเริ่ม free ได้
    healthCheckPath: /
    envVars:
      # URL ภายนอกของ ToolJet (เปลี่ยนทีหลังได้)
      - key: TOOLJET_HOST
        value: "https://tooljet.onrender.com"

      # ===== กรอกตอน Deploy (ห้าม commit ค่า) =====
      - key: LOCKBOX_MASTER_KEY    # 32 ไบต์ hex -> openssl rand -hex 32
        sync: false
      - key: SECRET_KEY_BASE       # 64 ไบต์ hex -> openssl rand -hex 64
        sync: false
      - key: DISABLE_TOOLJET_TELEMETRY
        value: "true"

      # ===== ToolJet ใช้ Postgres ที่ "มีอยู่แล้ว" =====
      # !! ชุดนี้คือ DB ภายในของ ToolJet เอง (metadata)
      - key: PG_HOST
        value: "YOUR_EXISTING_PG_HOST"
      - key: PG_PORT
        value: "5432"
      - key: PG_DB
        value: "tooljet_db"              # เราจะสร้าง DB นี้ใน instance เดิม
      - key: PG_USER
        value: "YOUR_EXISTING_PG_USER"
      - key: PG_PASS
        sync: false                      # รหัสของ user ข้างบน

      # ===== PostgREST (ใช้ DB เดียวกับ PG_DB) =====
      - key: PGRST_JWT_SECRET            # 32 ไบต์ hex
        sync: false
      - key: PGRST_DB_URI                # ตัวอย่าง: postgres://USER:PASS@HOST:5432/tooljet_db
        sync: false
