services:
  - type: web
    name: tooljet-app        # เปลี่ยนชื่อใหม่กันชนกับตัวเดิม
    runtime: image           # << สำคัญ: ใช้อิมเมจสาธารณะ ไม่ build จาก Dockerfile
    image: tooljet/tooljet-ce:latest
    plan: free               # ทดสอบเริ่ม free ได้
    healthCheckPath: /
    envVars:
      - key: TOOLJET_HOST
        value: "https://tooljet-app.onrender.com"   # เปลี่ยนภายหลังได้

      # ===== ให้กรอกตอน Deploy (ห้าม commit ค่า) =====
      - key: LOCKBOX_MASTER_KEY     # 32-byte hex -> openssl rand -hex 32
        sync: false
      - key: SECRET_KEY_BASE        # 64-byte hex -> openssl rand -hex 64
        sync: false
      - key: DISABLE_TOOLJET_TELEMETRY
        value: "true"

      # ===== ฐานข้อมูลภายใน ToolJet (ใช้ Postgres "ตัวที่มีอยู่แล้ว") =====
      - key: PG_HOST
        value: "YOUR_EXISTING_PG_HOST"
      - key: PG_PORT
        value: "5432"
      - key: PG_DB
        value: "tooljet_db"         # เราจะสร้าง DB นี้เพิ่มใน instance เดิม
      - key: PG_USER
        value: "YOUR_EXISTING_PG_USER"
      - key: PG_PASS
        sync: false                 # รหัสของ user ข้างบน

      # ===== PostgREST (ชี้ DB เดียวกับ PG_DB) =====
      - key: PGRST_JWT_SECRET       # 32-byte hex -> openssl rand -hex 32
        sync: false
      - key: PGRST_DB_URI           # ตัวอย่าง: postgres://USER:PASS@HOST:5432/tooljet_db
        sync: false
